FROM golang as exec

COPY app.go /go/src/app/

ENV GO111MODULE=auto

WORKDIR /go/src/app/

RUN go build -o app.go .

FROM alpine

WORKDIR /appexec

COPY --from=exec /go/src/app /appexec

RUN chmod -R 775 /appexec

ENTRYPOINT ./app.go


# To build and run...
# docker image build -t app-go:1.0 .
# docker run -ti --name meuappOK app-go:1.0